all:
  hosts:
    ficticio:
  children:
    BANCADA:
      hosts:
        VM-local:
          ansible_connection: ssh
          ansible_port: 22
          ansible_host: IP_DO_HOST_AQUI
          ansible_user: Usuario
          ansible_password: 123456
    LAB:
        children:
            LAB01:
              hosts:
                LAB01-HOST-1.meudominio:
                LAB01-HOST-2.meudominio:
            LAB02:
              hosts:
                LAB02-HOST-1.meudominio:
                LAB02-HOST-2.meudominio:
