- name: Criar diretório C:\ProgramData\SysInternals
  win_file:
    path: C:\ProgramData\SysInternals
    state: directory
  tags: lab,bginfo

- name: Download executavel Bginfo
  win_get_url:
    force: no
    url: '{{ srv_suporte_softwares }}/SysinternalsSuite/Bginfo.exe'
    dest: C:\ProgramData\SysInternals\Bginfo.exe
  tags: lab,bginfo

- name: Download Configuracao Bginfo
  win_get_url:
    force: yes
    url: '{{ srv_suporte}}/configuracoes/bginfo/bginfo.bgi'
    dest: C:\ProgramData\bginfo.bgi
  tags: lab,bginfo

- name: Download Papel de Parede Windows
  win_get_url:
    force: yes
    url: '{{ srv_suporte}}/configuracoes/papeis_de_parede/{{ papel_parede }}'
    # dest: C:\Windows\Web\Wallpaper\papel_parede.jpg
    dest: C:\Users\Public\Pictures\papel_parede.jpg
  tags: lab,bginfo

- name: Verificando se a chave existe
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\bginfo
  register: existe_chave_bginfo
  tags: lab,bginfo

- name: Deleta chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\bginfo
    state: absent
    delete_key: yes
  when: existe_chave_bginfo|bool
  tags: lab,bginfo

- name: Cria chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    name: bginfo
    data: 'C:\ProgramData\SysInternals\Bginfo.exe /iC:\ProgramData\bginfo.bgi /silent /timer:0 /accepteula'
    state: present
  tags: lab,bginfo
