- name: Verificando se a chave existe
  win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization\AllowPersonalization
  register: existe_chave
  tags: lab,personalizacao_windows

- name: Cria chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\ActiveDesktop
    name: AllowPersonalization
    data: 0
    type: dword
  when: not existe_chave.exists
  tags: lab,personalizacao_windows