- name: Cria chave RemoveWindowsStore no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    # path: HKCU:\Software\Policies\Microsoft\WindowsStore
    name: RemoveWindowsStore
    data: 1
    type: dword
  tags: lab,loja

- name: Cria chave DisableStoreApps no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    # path: HKCU:\Software\Policies\Microsoft\WindowsStore
    name: DisableStoreApps
    data: 1
    type: dword
  tags: lab,loja
