- name: Verificando se o arquivo existe no destino
  win_stat:
    path: C:\Windows\Fonts\LIBRAS_2012.TTF
  register: fonte
  tags: lab,fonte_windows_libras

- name: Verificando se a chave existe
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts\Libras 2012
  register: fonte_reg
  tags: lab,fonte_windows_libras

# - debug: msg="{{ fonte_reg }}"
#   tags: lab,fonte_windows_libras

- name: Instalação de Fontes para Windows
  win_get_url:
    url: '{{ url_http_softwares}}/Fontes/LIBRAS_2012.TTF'
    dest: C:\Windows\Fonts\LIBRAS_2012.TTF
  when: not fonte.stat.exists
  tags: lab,fonte_windows_libras

- name: Criação de registro para a fonte
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts
    name: Libras 2012
    data: LIBRAS_2012.TTF
    type: string
    state: present
  when: not fonte_reg.exists
  tags: lab,fonte_windows_libras
