# Verificar se esta instalado
- name: Verificando se OCSInventory esta instalado
  win_reg_stat:
    path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\OCS Inventory NG Agent
  register: ocs_instalado
  tags: lab,ocs

# Instalar
- name: Instalar OCSInventory
  win_package:
    path: "{{ srv_suporte_softwares }}/{{ pkg_ocs }}"
    product_id: '{}'
    arguments: /S /NOSPLASH /UPGRADE /UID /NOW /FORCE /hkcu=1 /SSL=0 /SERVER={{ ocs_server }} /TAG={{ ocs_tag }}
    state: present
  when: (ocs_instalado.exists == False) or (FORCE is defined) or (ocs_instalado.properties.DisplayVersion.value != "2.6.0.0")
  ignore_errors: True
  tags: lab,ocs
