- name: Verificando se a chave existe
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA
  register: existe_chave_uac
  tags: windows-uac

- name: Deleta chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    state: absent
    delete_key: yes
  when: existe_chave_uac
  tags: windows-uac

- name: Cria chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    data: 1
    state: present
    type: dword
  tags: windows-uac

- name: Cria chave no registro do windows
  win_regedit:
    path: HKLM:\SOFTWARE\Classes\Msi.Package
    name: DefaultIcon
    data: 0
    state: present
    # type: dword
  tags: windows-uac
